#!/bin/bash
source coinlist
count=0

while [ "x${coinlist[count]}" != "x" ]
do
  all=${coinlist[count]}
  name=${all%% *}
  if [ "$name" != "" ]
    then
     echo $name
     processinfo=$(ps aux | grep $name | grep gen)
     pid=$(echo $processinfo | awk '{print $2}')
     cpulimit -p $pid -l 33 -b
  fi
  count=$(( $count +1 ))
done
