#!/bin/bash
#cd ~/scaletest

chainstart=0
chainend=63
dpowfile=startdpow

source coinlist

while [[ (! -z ${2+x} && $count -le $chainend) || (-z ${2+x} && $count -le ${#coinlist[@]}) ]]
do
    all=${coinlist[count]}
    name=${all%% *}
    if [ "$name" != "" ]
    then
       coin7776="COINS_7776/"
       coin7776+=$name
       coin7776+="_7776"
       cat $coin7776 >> m_notary_scale
       echo $'\n' >> m_notary_scale
       #Make dPow file add to m_notary_scale at the end
       dpow='curl --url "http://127.0.0.1:7776" --data "{\"timeout\":60000,\"agent\":\"iguana\",\"method\":\"dpow\",\"symbol\":\"'
       dpow+=$name
       dpow+='\",\"pubkey\":\"$pubkey\"}"'
       echo $dpow >> $dpowfile
    fi
    count=$(( $count +1 ))
done

echo "sleep 3" >> m_notary_scale
cat $dpowfile >> m_notary_scale
